---

- name: Install required modules
  yum:
    name: "{{ required-modules }}"
    state: present

- name: Create SSL dir
  file:
    path: /etc/postfix/ssl
    state: directory
    owner: root
    group: root

- name: Generate an OpenSSL private key
  vars:
    ansible_python_interpreter: /usr/bin/python3
  openssl_privatekey:
    path: /etc/postfix/ssl/server-key.pem

- name: Get information on generated key
  vars:
    ansible_python_interpreter: /usr/bin/python3
  openssl_privatekey_info:
    path: /etc/postfix/ssl/server-key.pem
  register: result

- name: Dump information
  debug:
    var: result

- name: Generate an OpenSSL CSR
  vars:
    ansible_python_interpreter: /usr/bin/python3
  openssl_csr:
    path: /etc/postfix/ssl/server-key.csr
    privatekey_path: /etc/postfix/ssl/server-key.pem